/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Assignment.Matthew.Ettridge;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
